// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdpebeydrdzkboydfmys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcGViZXlkcmR6a2JveWRmbXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjQ2MTksImV4cCI6MjA2NjQwMDYxOX0.VYynmz3jtLFFvD8WNJYI_zp8gnxyhhCkbieDJEJ_jP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);